[qarma]
source = "github"
github = "luebking/qarma"
use_max_tag = true
prefix = "v"

[hstr]
source = "github"
github = "dvorka/hstr"
use_max_tag = true
prefix = "v"

[kitty-bin]
source = "github"
github = "kovidgoyal/kitty"
use_latest_release = true
prefix = "v"

["llama.cpp-vulkan"]
source = "github"
github = "ggml-org/llama.cpp"
use_latest_release = true

[opencode-bin]
source = "github"
github = "anomalyco/opencode"
use_latest_release = true
prefix = "v"

[r8125]
source = "jq"
url = "https://www.realtek.com/Download/ListAllDownloadItem?cate_id=584"
filter = '.Data.DownloadItems["Unix (Linux)"][] | select(.Name | startswith("r8125")) | .Version'

[Kvantum]
source = "github"
github = "tsujan/Kvantum"
use_latest_release = true

[gitleaks]
source = "github"
github = "gitleaks/gitleaks"
use_latest_release = true

[discord]
source = "httpheader"
url = "https://discord.com/api/download?platform=linux&format=tar.gz"
regex = "discord-(.*)\\.tar.*"

[Signal]
source = "github"
github = "signalapp/Signal-Desktop"
use_latest_release = true

