[qarma]
source = "github"
github = "luebking/qarma"
use_max_tag = true
prefix = "v"

[hstr]
source = "github"
github = "dvorka/hstr"
use_max_tag = true
prefix = "v"

[kitty-bin]
source = "github"
github = "kovidgoyal/kitty"
use_latest_release = true
prefix = "v"

["llama.cpp-vulkan"]
source = "github"
github = "ggml-org/llama.cpp"
use_latest_release = true

[opencode-bin]
source = "github"
github = "anomalyco/opencode"
use_latest_release = true
prefix = "v"
