[qarma]
source = "github"
github = "luebking/qarma"
use_max_tag = true
prefix = "v"

[hstr]
source = "github"
github = "dvorka/hstr"
use_max_tag = true
prefix = "v"

[kitty-bin]
source = "github"
github = "kovidgoyal/kitty"
use_latest_release = true
prefix = "v"

["llama.cpp-vulkan"]
source = "github"
github = "ggml-org/llama.cpp"
use_latest_release = true

[opencode-bin]
source = "github"
github = "anomalyco/opencode"
use_latest_release = true
prefix = "v"

[r8125]
source = "jq"
url = "https://www.realtek.com/Download/ListAllDownloadItem?cate_id=584"
filter = '.Data.DownloadItems["Unix (Linux)"][] | select(.Name | startswith("r8125")) | .Version'

[Kvantum]
source = "github"
github = "tsujan/Kvantum"
use_latest_release = true

[gitleaks]
source = "github"
github = "gitleaks/gitleaks"
use_latest_release = true

[discord]
source = "httpheader"
url = "https://discord.com/api/download?platform=linux&format=tar.gz"
regex = "discord-(.*)\\.tar.*"

[solvespace]
source = "github"
github = "solvespace/solvespace"
use_latest_release = true
prefix = "v"

[gamescope]
source = "github"
github = "ValveSoftware/gamescope"
use_max_tag = true

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"
use_max_tag = true
prefix = "v"

[python3-structlog]
source = "pypi"
pypi = "structlog"

[python3-platformdirs]
source = "pypi"
pypi = "platformdirs"

[python3-awesomeversion]
source = "pypi"
pypi = "awesomeversion"

[python3-fsspec]
source = "github"
github = "fsspec/filesystem_spec"
use_max_tag = true

[python3-packaging]
source = "github"
github = "pypa/packaging"
use_max_tag = true

[python3-annotated-doc]
source = "pypi"
pypi = "annotated-doc"

[python3-typer]
source = "pypi"
pypi = "typer"

[python3-huggingface_hub]
source = "pypi"
pypi = "huggingface_hub"

[click]
source = "github"
github = "mitsuhiko/click"
use_max_tag = true

[playwright-cli]
source = "npm"
npm = "@playwright/cli"

[firefly-cli]
source = "github"
github = "danixland/firefly-cli"
use_max_tag = true
prefix = "v"

[UrbanTerror]
source = "regex"
url = "https://www.urbanterror.info/downloads/"
regex = "UrbanTerror(\\d+)_full\\.zip"
from_pattern = "(\\d)(\\d)(\\d)"
to_pattern = "\\1.\\2.\\3"
